name: Sequence Conversion Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  convert_sequence:
    name: Convert Sequence Data
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install argparse

    - name: Run Conversion Script Fasta to Nexus
      run: python Converter_ap_BioP.py data/RAG1_aligned.fasta data/RAG1_aligned.nexus
      
    - name: Run Conversion Fasta to Phylip
      run: python Converter_ap_BioP.py data/RAG1_aligned.fasta data/RAG1_aligned.phy
      
    - name: Run Conversion Script Nexus to Fasta
      run: python Converter_ap_BioP.py data/RAG1_aligned.nexus data/RAG1_aligned.fasta

    - name: Run Conversion Script Nexus to Phylip
      run: python Converter_ap_BioP.py data/RAG1_aligned.nexus data/RAG1_aligned.phy
 
    - name: Run Conversion Script Phylip to Fasta
      run: python Converter_ap_BioP.py data/RAG1_aligned.phy data/RAG1_aligned.fasta
      
    - name: Run Conversion Script Phylip to Nexus
      run: python Converter_ap_BioP.py data/RAG1_aligned.phy data/RAG1_aligned.nexus


    
    

